[PDF]
#qbroad = 9.44564318e-03
#qdamp =  2.21325581e-02
[Measurement]
keV = 59.798
[R_val]
rmin = 1.2
rmax = 200
rstep = 0.01
[files]
cifs = '../../CIFS/'
out = './results/'
[Verbose]
step = true
results = true

[Restraints]
delta2 = [0.0, 8.0, 1.0]
scale = [0.0, 1.0, 0.1]
adp = [0.0, 0.5, 0.1]
cfs = [0.0, 100.0, 50.0]
occ = [0.0, 1.0, 1.0]
lat = 0.5


[[param_order]]
free = ["lat", "scale"]
fix = []

[[param_order]]
free = ["cfs", "occ"] 
fix = []

[[param_order]]
free = ["delta2", "adp"]
fix = []
